### ISSUE TITLE
[Audio balance] A bunch of sounds files are very loud

### ISSUE THREAD

**Issue by JohnMetroid** [PlasteredCrab/BlackMesa#3]
Hey there,

Congrats on the 3.0.0 release, the map/interior are great.  Just a heads up that a number of the sound files are normalized quite a bit louder than LC audio.

Specifically: The intro audio clip that plays when landing, the aperture science elevator jingle, and the sliding door open/close audio (door type shown below).

Cheers

![image](https://github.com/user-attachments/assets/c9eb92d8-7dc2-4e8a-96ce-c4128d07b5b0)

edit: and while not strictly a bug report, I'd love if there was more clarity on blocked doors.  It seems like you're using light boarding and some hazard signs to indicated blocked doors, but some blocked paths don't seem to have any indicator on the door at all (?).  It would be nice if you could lean into the boarding off idea and just use that uniformly, and make the boards really thick and cover the full door.  Would make navigating the interior a lot more intuitive

**Comment by Zaggy1024** [comment]
Volume levels for the doors were adjusted in a previous version, but I've just lowered the intro audio a bit, and the elevator jingle significantly, hopefully that makes things a little nicer. That'll be live in 3.1.0 whenever it becomes available.

> edit: and while not strictly a bug report, I'd love if there was more clarity on blocked doors. It seems like you're using light boarding and some hazard signs to indicated blocked doors, but some blocked paths don't seem to have any indicator on the door at all (?). It would be nice if you could lean into the boarding off idea and just use that uniformly, and make the boards really thick and cover the full door. Would make navigating the interior a lot more intuitive

I'm open to seeing specific examples of which ones you find especially problematic so that we can re-evaluate this, but currently we're pretty happy with the readability of the blockers. The main goal was to make it so that you don't have to walk too far before you can see that a door is blocked, which I think we've at least _mostly_ achieved. If there are some that lack any indicators, that would be worth addressing for sure.

If you want to follow up, though, please do so in another bug with some example screenshots so that we can figure out if there are any specific improvements we can make.

**Comment by JohnMetroid** [comment]
Hey zaggy,

Thanks for the reply and fixes.  Everything sounds a **lot** better.  The intro line and door sfx are perfect.  The elevator is definitely much more pleasant, though it still seems a tiny bit loud when standing inside of it (maybe ~0.5-1db too high, it's a bit overbearing when trying to talk to people)

As for the blocked doors, I can open a new issue if you want, but it seems like you've already decided against any changes so I'll just leave a quick followup here.  I think there's a strong case to be made for using a single, uniform scheme for indicating blocked doors.  Doors with an administrative sign/note don't really reach the threshold for clarity, in my opinion.  I've lost count of the times I've seen crew members walk up to these doors and try to interact with them even after spending a significant amount of time on Black Mesa.  I think Black Mesa would benefit from relying exclusively on boarding up the doors, and going a little bit harder on this concept by fully boarding up the door.

![image](https://github.com/user-attachments/assets/13aae396-8d51-46c6-8eee-4ca7ca749d8b)

A few examples of doors I don't think meet the bar for clarity from a distance or at a quick glance

![image](https://github.com/user-attachments/assets/9da14ae4-6fae-4401-bf24-c6a7b20fa95b)
![image](https://github.com/user-attachments/assets/27f4e268-2744-405e-9834-b4a8f124ac87)
![image](https://github.com/user-attachments/assets/c62830e7-f346-49f8-9054-4cf45e3e3eba)
![image](https://github.com/user-attachments/assets/48d47a20-317e-4971-ab68-0aec5ff526b6)
![image](https://github.com/user-attachments/assets/4491f51e-dd44-44ff-8d2a-4f19d4d86ece)

Also, as a minor note, it seems like when walking into the shallow part of a vent, the player will always hold up their hands as if they are hitting a solid wall before proceeding

![image](https://github.com/user-attachments/assets/e958ade1-702b-436a-b5ca-c4f276db2bc1)
![image](https://github.com/user-attachments/assets/67bc9e1e-8cc9-4d8f-8d70-3c0f224539ba)

Cheers
